Update deploy-postmetastore.yml for Azure Pipelines

diff --git a/iac-adb-360/pipelines/azure/deploy-postmetastore.yml b/iac-adb-360/pipelines/azure/deploy-postmetastore.yml
--- a/iac-adb-360/pipelines/azure/deploy-postmetastore.yml
+++ b/iac-adb-360/pipelines/azure/deploy-postmetastore.yml
@@ -29,12 +29,12 @@ stages:
       inputs:
         script: |
           - script: |
-          if ! command -v databricks &> /dev/null; then
-            echo "Databricks CLI not found. Installing..."
-            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
-          else
-            echo "Databricks CLI already installed. Skipping installation."
-          fi
+            if ! command -v databricks &> /dev/null; then
+              echo "Databricks CLI not found. Installing..."
+              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
+            else
+              echo "Databricks CLI already installed. Skipping installation."
+            fi
           displayName: 'Check and Install Databricks CLI'
       displayName: 'Install Databricks CLI v2 with sudo'
 
