iii

diff --git a/iac-adb-360/pipelines/azure/deploy-postmetastorecombined.yml b/iac-adb-360/pipelines/azure/deploy-postmetastorecombined.yml
--- a/iac-adb-360/pipelines/azure/deploy-postmetastorecombined.yml
+++ b/iac-adb-360/pipelines/azure/deploy-postmetastorecombined.yml
@@ -69,8 +69,7 @@ stages:
     pool:
       name: jensazureagentpool
     steps:
-    - checkout: self
-
+    - checkout: self    
     - task: CmdLine@2
       displayName: 'Install Databricks CLI v2 (sudo)'
       inputs:
@@ -85,33 +84,33 @@ stages:
           curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
           databricks version
 
-    - script: |
-          set -euo pipefail
-          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-          if ! command -v az >/dev/null 2>&1; then
-            echo "Azure CLI not found. Installing..."
-            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-            az config set extension.dynamic_install_allow_preview=true
+  - task: CmdLine@2
+    displayName: 'Uninstall & Install Azure CLI'
+    inputs:
+      script: |
+        set -euo pipefail
+  
+        echo "Checking for existing Azure CLI installation..."
+        if command -v az >/dev/null 2>&1; then
+          echo "Azure CLI found. Uninstalling..."
+          sudo apt-get remove -y azure-cli
+        else
+          echo "Azure CLI not found. Proceeding with fresh install
+  
+  - task: AzureCLI@2
+    displayName: 'Create catalog+schema (separate storage)'
+    inputs:
+      azureSubscription: 'ado-sc'
+      scriptType: bash
+      scriptLocation: scriptPath
+      scriptPath: './iac-adb-360/helpers/create-ms-catalognschema-sepstor.sh'
+      arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(catalogstorageaccountname) $(credname) $(accessconnectorid)'
 
-          else
-            echo "Azure CLI already installed. Skipping."
-          fi
-      displayName: 'Check & install Azure CLI'
-      
-    - task: AzureCLI@2
-      displayName: 'Create catalog+schema (separate storage)'
-      inputs:
-        azureSubscription: 'ado-sc'
-        scriptType: bash
-        scriptLocation: scriptPath
-        scriptPath: './iac-adb-360/helpers/create-ms-catalognschema-sepstor.sh'
-        arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(catalogstorageaccountname) $(credname) $(accessconnectorid)'
-
-    - task: AzureCLI@2
-      displayName: 'Create external location'
-      inputs:
-        azureSubscription: 'ado-sc'
-        scriptType: bash
-        scriptLocation: scriptPath
-        scriptPath: './iac-adb-360/helpers/create-ms-externallocation.sh'
-        arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(bronzestorageaccountname) $(credname) $(accessconnectorid)'
+  - task: AzureCLI@2
+    displayName: 'Create external location'
+    inputs:
+      azureSubscription: 'ado-sc'
+      scriptType: bash
+      scriptLocation: scriptPath
+      scriptPath: './iac-adb-360/helpers/create-ms-externallocation.sh'
+      arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(bronzestorageaccountname) $(credname) $(accessconnectorid)'
